<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'view-dashboard',
            'view-dashboard-kamar',
            'view-user',
            'view-settings',
            'view-menus',
            'view-perusahaan',
            'view-role-permission',
            'view-roles',
            'view-permissions',
            'add-menu',
            'view-karyawan',
            'view-master',
            'view-bagian',
            'view-jabatan',
            'view-ruangan',
            'view-spesialis',
            'create-cuti-other-karyawan',
            'view-surat',
            'view-cuti',
            'view-sp3',
            'view-supplier',
            'view-jasmed',
            'view-kategori-barang',
            'view-satuan-barang',
            'view-penyimpanan',
            'view-barang',
            'view-pembelian',
            'view-distribusi',
            'view-gudang',
            'view-asset',
            'view-hutang',
            'view-piutang',
            'view-laporang',
            'view-stok-opname',
            'view-laporan',
            'export-karyawan',
            'view-dokter',
            'edit-karyawan',
            'tanda-tangan-digital',
            'view-verifikasi',
            'view-maintenance',
            'approval-maintenance',
            'jasmed-bpjs',
            'jasmed-jkmd',
            'view-pengajuan',
            'finish-opname-gudang',
            'view-akreditasi',
            'assesor-akreditasi',
            'view-pengaturan-cuti',
            'view-kepegawaian-master-cuti-index',
            'add-kepegawaian-master-cuti-index',
            'edit-kepegawaian-master-cuti-index',
            'delete-kepegawaian-master-cuti-index',
            'view-kepegawaian-surat-cuti',
            'add-kepegawaian-surat-cuti',
            'edit-kepegawaian-surat-cuti',
            'delete-kepegawaian-surat-cuti',
            'view-admin-user-index',
            'view-admin-settings-menu',
            'view-admin-settings-perusahaan',
            'view-admin-settings-role',
            'view-admin-user',
            'view-admin-settings-permission',
            'view-kepegawaian-karyawan',
            'edit-kepegawaian-karyawan',
            'view-kepegawaian-master-bagian',
            'view-kepegawaian-master-jabatan',
            'view-kepegawaian-master-ruangan',
            'view-kepegawaian-master-spesialisasi',
            'view-kepegawaian-surat-sp3',
            'view-umum-master-supplier',
            'view-kepegawaian-jasmed',
            'view-umum-master-kategori',
            'view-umum-master-satuan',
            'view-umum-master-penyimpanan',
            'view-umum-master-barang',
            'view-umum-pembelian',
            'view-umum-distribusi',
            'view-umum-gudang',
            'view-umum-asset',
            'view-keuangan-hutang',
            'view-keuangan-piutang',
            'view-umum-laporan',
            'view-umum-opname',
            'view-keuangan-laporan',
            'view-surat-verification',
            'view-umum-maintenance',
            'view-umum-pengajuan',
            'view-kepegawaian-laporan',
            'view-kepegawaian-akreditasi',
            'view-kepegawaian-master-cuti',
            'view-keuangan-akuntansi-coa',
            'view-keuangan-akuntansi-jurnal-umum',
            'view-keuangan-master-rekanan',
            'add-keuangan-master-rekanan',
            'edit-keuangan-master-rekanan',
            'delete-keuangan-master-rekanan',
            'view-kepegawaian-gaji',
            'view-administrasi-pasien-index',
            'add-administrasi-pasien-index',
            'edit-administrasi-pasien-index',
            'delete-administrasi-pasien-index',
            'view-kepegawaian-gaji-index',
            'add-kepegawaian-gaji-index',
            'edit-kepegawaian-gaji-index',
            'delete-kepegawaian-gaji-index',
            'view-administrasi-registrasi-index',
            'add-administrasi-registrasi-index',
            'edit-administrasi-registrasi-index',
            'delete-administrasi-registrasi-index'
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }
    }
}
